version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sugnu_hotel_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgsql_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sugnu_hotel_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "composer install && php artisan migrate:fresh --seed --force && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sugnu_hotel_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && ng serve --host 0.0.0.0 --poll 2000"
    depends_on:
      - backend

volumes:
  pgsql_data:
